name: gg_install_gg
description: gg_install_gg installs the gg developer command line locally.
version: 1.0.8
repository: https://github.com/inlavigo/gg_install_gg.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^2.0.0
  gg_console_colors: ^2.0.2
  gg_log: ^1.0.0
  gg_process: ^1.0.7
  mocktail: ^1.0.3
  path: ^1.8.0

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^3.0.0
  test: ^1.24.0
  colorize: any

executables:
  gg_install_gg: